import { env } from 'cloudflare:workers';
export const db=()=>{if(!env.DB)throw new Error('Database unavailable');return env.DB};
export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function password(value:string,salt=uid()){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return salt+':'+Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function verify(value:string,stored:string){const result=await password(value,stored.split(':')[0]);let diff=result.length^stored.length;for(let i=0;i<result.length;i++)diff|=result.charCodeAt(i)^stored.charCodeAt(i);return diff===0}
export async function audit(actor:string,action:string,object:string){return db().prepare('INSERT INTO logs VALUES (?,?,?,?,?)').bind(uid(),actor,action,object,now()).run()}
export async function seed(){if(await db().prepare("SELECT id FROM settings WHERE id='initialized'").first())return;const date=now();const accounts=[['demo-admin','Алия Садыкова','admin@mini-crm.test','Admin'],['demo-employee','Данияр Ибраев','employee@mini-crm.test','Employee'],['demo-client','Алексей Смирнов','client@mini-crm.test','Client']];const hashes=await Promise.all(accounts.map(()=>password('CrmDemo!2026')));const statements=accounts.map((a,i)=>db().prepare('INSERT OR IGNORE INTO users (id,name,email,password,role,created) VALUES (?,?,?,?,?,?)').bind(...a.slice(0,3),hashes[i],a[3],date));const samples=[['c1','demo-client','Алексей Смирнов','client@mini-crm.test','+7 701 234 56 78','Смирнов & партнёры','IN_PROGRESS','HIGH'],['c2',null,'Мария Иванова','maria@example.com','+7 702 456 78 90','Studio Forma','NEW','NORMAL'],['c3',null,'Тимур Ахметов','timur@example.com','+7 705 123 45 67','Qazaq Logistics','SUCCESS','HIGH'],['c4',null,'Елена Ким','elena@example.com','+7 777 321 00 11','Kim Consulting','IN_PROGRESS','NORMAL'],['c5',null,'Руслан Омаров','ruslan@example.com','','Orion Group','LOST','NORMAL'],['c6',null,'Анна Петрова','anna@example.com','','North Design','NEW','NORMAL']];for(const a of samples)statements.push(db().prepare('INSERT OR IGNORE INTO clients VALUES (?,?,?,?,?,?,?,?,?,?)').bind(...a,date,date));statements.push(db().prepare('INSERT OR IGNORE INTO notes VALUES (?,?,?,?,?,?)').bind('welcome','c1','Алия Садыкова','Здравствуйте! Готовим предложение для вашей компании. Свяжемся с вами в ближайшее время.',1,date),db().prepare('INSERT OR IGNORE INTO notes VALUES (?,?,?,?,?,?)').bind('internal','c1','Данияр Ибраев','Обсудить условия договора на следующей встрече.',0,date),db().prepare("INSERT OR IGNORE INTO settings VALUES ('company','Orbit CRM')"),db().prepare("INSERT OR IGNORE INTO settings VALUES ('initialized','1')"));await db().batch(statements)}
